spring.application.name=eureka-server
server.port=${SERVER_PORT:8761}

# Eureka server should not register itself or fetch registry entries.
eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTERWITHEUREKA:false}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCHREGISTRY:false}
